# Generated by Django 4.0.4 on 2022-04-30 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('details', models.TextField(blank=True)),
                ('rate', models.IntegerField(null=True)),
                ('total_target', models.IntegerField()),
                ('current_donation', models.IntegerField(default=0)),
                ('start_campaign', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_campaign', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('selected_at_by_admin', models.DateTimeField(null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.categories')),
            ],
        ),
    ]
