# Generated by Django 4.0.4 on 2022-04-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donations',
            name='paid_up',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='selected_at_by_admin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='replie',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.comments'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='replie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.replies'),
        ),
    ]
