# Generated by Django 4.0.4 on 2022-05-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(max_length=255, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projects'),
        ),
    ]
