# Generated by Django 4.0.4 on 2022-05-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='paid_up',
            field=models.IntegerField(default=0),
        ),
    ]
