# Generated by Django 4.0.4 on 2022-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('mobile_phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(null=True)),
            ],
        ),
    ]
