# Generated by Django 4.0.4 on 2022-05-05 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^01[0-2,5]{1}[0-9]{8}$')]),
        ),
    ]
