# Generated by Django 4.0.4 on 2022-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(max_length=255, null=True, upload_to='img/%y'),
        ),
    ]
