# Generated by Django 4.0.4 on 2022-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verifications',
            field=models.BooleanField(default=False),
        ),
    ]
