# Generated by Django 4.0.4 on 2022-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_birth_date_user_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/%y'),
        ),
    ]
