# Generated by Django 4.0.4 on 2022-05-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
